### ISSUE TITLE
other gem

### ISSUE THREAD

**Issue by woodhull** [EricBoersma/actionkit_connector#1]
Just making sure you knew that we already had an open source gem: https://github.com/controlshift/action_kit_rest

**Comment by EricBoersma** [comment]
Thanks for pointing this out!

—
Eric Boersma
Director of Engineering, SumOfUs
616-403-9209 (Grand Rapids, MI)
Skype: eric_sou

On May 13, 2015 at 9:31:15 AM, Nathan Woodhull (notifications@github.com) wrote:

Just making sure you knew that we already had an open source gem: https://github.com/controlshift/action_kit_rest
